#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_doc:
    path: /docs/api
    controller: api_platform.swagger.action.ui

authentication_token:
    path: /api/login_check
    methods: ['POST']